### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by nurhalim88** [dohsimpson/HabitTrove#2]
Hi, are there any plans for a regular Docker image with Compose support? I'd love to try it out.

**Comment by dohsimpson** [comment]
Hi @nurhalim88 , you mean like a pre-built docker image? You could run `docker run -p 3000:3000 -v $(pwd)/data:/app/data dohsimpson/habittrove` which will pull the latest image from dockerhub.

**Comment by dohsimpson** [comment]
For compose file, you could try something like this:

```
version: '3.3'
services:
    habittrove:
        ports:
            - '3000:3000'
        volumes:
            - '$(pwd)/data:/app/data'
        image: dohsimpson/habittrove
```
